---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.3.0
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: false
    checksum: false
    download: false
    fetch: true
    git: true
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: true
    system: false
    tags: true
    version: true
app_desc: ' command-line utility that creates projects from cookiecutters (project
    templates).'
app_name: cookiecutter
app_repo: https://github.com/cookiecutter/cookiecutter
app_type: python
app_website: https://cookiecutter.readthedocs.io/en/stable/README.html
checksum_enabled: false
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: python
gpg_enabled: false
install_map_enabled: true
install_map_method: link
install_map_yaml:
    venv/bin/cookiecutter: bin/cookiecutter
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-cookiecutter
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-cookiecutter.git
python_name: cookiecutter
source_enabled: true
source_type: git
source_url: https://github.com/cookiecutter/cookiecutter.git
test_cmd_args: --version
version_file_enabled: false
version_prefix: ''
